### ISSUE TITLE
Can't find the files!

### ISSUE THREAD

**Issue by abhigenie92** [sindresorhus/trash-cli#10]
Using zsh on kubuntu 16.04.
```
 ✘  ~  sudo npm install --global trash-cli
/usr/local/bin/trash -> /usr/local/lib/node_modules/trash-cli/cli.js
/usr/local/lib
`-- trash-cli@1.3.0 

 ~  take new
 ~/new  .. 
 ~  trash new
/usr/bin/env: ‘node’: No such file or directory
 ~  touch hello
 ~  trash hello
/usr/bin/env: ‘node’: No such file or directory

```

**Comment by SamVerschueren** [comment]
What does `node -v` gives you?

Also using `sudo` to install global packages is not really a good option. Checkout [this](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md) read.

**Comment by abhigenie92** [comment]
```
node -v
The program 'node' is currently not installed. You can install it by typing:
sudo apt install nodejs-legacy
zsh: command not found: node
```
I installed `nodejs-legacy` now it shows no error, but the files are not present in the trash.

**Comment by SamVerschueren** [comment]
Might be better to checkout [this](https://nodejs.org/en/download/package-manager/) page in order to install Node.js on linux.
