### ISSUE TITLE
Add restore feature

### ISSUE THREAD

**Issue by zaaack** [sindresorhus/trash-cli#15]
Like `restore -last`, `restore -last=<n>`, n means the last nth file/folder removed to trash.

**Comment by sindresorhus** [comment]
Blocked by https://github.com/sindresorhus/trash/issues/24 (Which is a long standing macOS bug...)

**Comment by zaaack** [comment]
@sindresorhus What a pity..

**Comment by zaaack** [comment]
@sindresorhus Can we store the original file's directory and just `mv ~/.Trash/<lastFile> <lastDirectory>`?

**Comment by sindresorhus** [comment]
No, macOS renames duplicates in the trash, so original filenames are not guaranteed. The only workaround, as discussed in the original issue, is to parse the undocumented `.DS_Store` file, but that's not something I have time or interest in doing.

**Comment by zaaack** [comment]
@sindresorhus We can rename duplicates manually before putting to trash.

**Comment by sindresorhus** [comment]
That's a slippery slope. And our mapping will easily get out of sync when the user trashes and restores in Finder, which we can't know about.

**Comment by zaaack** [comment]
@sindresorhus But this wouldn't be a huge problem? We can rename with timestamp and rand id each time, If the user restores in Finder, then it's handled by the user, he or she will know what he or she is doing since he is already using the command line. And if we cannot find the renamed file in Trash, we can print some message to show what happened.

**Comment by sindresorhus** [comment]
Yes, I guess that would work, but it's not something I would be interested in maintaining.

**Comment by zaaack** [comment]
@sindresorhus Fair enough.
