### ISSUE TITLE
Restoring issue

### ISSUE THREAD

**Issue by theolaurent** [sindresorhus/trash-cli#16]
It seems that trash-cli do weird stuff with symlinks.
I have a Download folder on a separate partition, wich I symlinked to my home folder.
If I `trash-put file` inside it, I am not able to restore the file with `trash-restore`; neither from /home/user/Download nor /mountpoint/Download.

EDIT: it seems that I am unable to restore files trashed on this partition.

**Comment by sant123** [comment]
This is expected since partitions doesn't have a 'trash'. You can check it out plugging a pendrive and try deleting files by yourself. You will see that the file will be permanently deleted instead of moving it to the trash.

**Comment by russelldavis** [comment]
Pretty sure this issue was mistakenly filed here instead of https://github.com/andreafrancia/trash-cli (this repo does not provide `trash-put` or `trash-restore` commands).
