### ISSUE TITLE
Feature: Compile trash-cli into native binaries

### ISSUE THREAD

**Issue by MironVeryanskiy** [sindresorhus/trash-cli#18]
**Issue:**
Some systems do not have the liberty to run/install node. This prevents being able to easily provision trash-cli on these systems.

**Request**
Update release flow to release compiled binaries.
This can be accomplished using npm's pkg ([https://www.npmjs.com/package/pkg](https://www.npmjs.com/package/pkg))

**Comment by sindresorhus** [comment]
Feel free to do that if you need it, but I'm not going to.

If you're on macOS or Windows, you could use the native binaries directly:

- https://github.com/sindresorhus/macos-trash
- https://github.com/sindresorhus/recycle-bin

**Comment by MironVeryanskiy** [comment]
If you find it has value, I'm up for implementing this and submitting a PR at some point in the future...but I'm a bit naive here. Can you shine some light on why you see this as less trivial than it appears? Or is there another other reason for avoiding this feature?
