### ISSUE TITLE
project name causes confusion with the original trash-cli project (in Python)

### ISSUE THREAD

**Issue by andreafrancia** [sindresorhus/trash-cli#33]
Hi @sindresorhus please be aware that the name you choose for the project can cause confusion in users as it is the same of my trash-cli project [1].

As a example I found this issue [2] in my trash-cli project 

[1] https://github.com/andreafrancia/trash-cli
[2] https://github.com/andreafrancia/trash-cli/issues/155

**Comment by sindresorhus** [comment]
There are lots of packages named the same across different programming languages. I don't really see the problem. I use `trash-cli` as my convention is to use `foo` for the library part and `foo-cli` for the CLI part. I don't plan to change the name of this package.
