### ISSUE TITLE
Add example unicorn.png

### ISSUE THREAD

**Issue by rawtaz** [sindresorhus/trash-cli#36]
In the `readme.md` of this repository there's a reference to a file named `unicorn.png`.

Considering that this tool (`trash`) is amazing, simple logic tells us that the unicorn must also be amazing.

For purposes of:

- amazing,
- reference,
- removal of ambiguity,

please include the (amazing) `unicorn.png` image file in this repository. Thank you.

**Comment by sindresorhus** [comment]
I don't intend to add that to this repo, but here's a unicorn for you: http://sindresorhus.com/unicorn
