### ISSUE TITLE
Error: EACCES: permission denied

### ISSUE THREAD

**Issue by sivabudh** [sindresorhus/trash-cli#4]
Hello,

For some reason, when I invoke `trash`, it reports an error like this. See: https://gist.github.com/sivabudh/7fc1d56d3cb283b193b9

When I did `sudo trash`, then, it was okay.

I installed `npm` via `nvm`. See:
https://gist.github.com/0f1416b3337f54d0158d

**Comment by SamVerschueren** [comment]
It seems like a permission issue on your system. Don't think it has anything to do with this plugin.

**Comment by sindresorhus** [comment]
Yeah, you need to fix the permission on the referenced file.

**Comment by sivabudh** [comment]
@SamVerschueren and @sindresorhus. Thanks. I went in an manually deleted the offending file. Then, I re-installed `trash-cli` via `npm` again and now it works fine. =)

Thanks!
