### ISSUE TITLE
To alias, or not to alias

### ISSUE THREAD

**Issue by louisremi** [sindresorhus/trash-cli#7]
Unless there's a distinction I do not understand, the Readme both advise aliasing `rm` to `trash`... and not doing it.

> You should not alias rm to trash however as that would break most scripts relying on rm behavior.

> Add alias rm=trash to your .zshrc/.bashrc to reduce typing & safely trash files: $ rm unicorn.png.

**Comment by sindresorhus** [comment]
The first is wrong. I guess when I wrote this I was not aware aliases doesn't apply in scripts, but only when run interactively.

**Comment by louisremi** [comment]
Perfect!
